name: Translater
description: A translator app that keeps track of all the new words you are learning.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  path_provider: ^0.4.1
  http: ^0.13.3
  charts_flutter: ^0.5.0
  xml: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/sampledata.json
    - assets/deu-eng.csv
    - assets/eng-deu.csv
